### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server-router#2] opened 2018-03-12 22:12 UTC
Documentation should be added, see https://github.com/amphp/amphp.github.io#setup-for-a-new-repository for a guide and have a look at other repositories for how it works.

**Comment by kellyhibbs** [comment] 2020-05-02 07:22
#7 

> []() @
Duplicate of _#_

**Comment by trowski** [comment] 2023-08-05 17:34
Added documentation to the readme.

**Closed by trowski** 2023-08-05 17:34 UTC
Labels: documentation, hacktoberfest
